"""drop event_count columns

Revision ID: 0493fe4fb600
Revises: c998c87a60cf
Create Date: 2026-08-31 12:17:09.238183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0493fe4fb600'
down_revision: Union[str, Sequence[str], None] = 'c998c87a60cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installation', 'event_count')
    op.drop_column('pruned_installation', 'event_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pruned_installation', sa.Column('event_count', sa.INTEGER(), server_default='0', nullable=False))
    op.add_column('installation', sa.Column('event_count', sa.INTEGER(), server_default='1', nullable=False))
    # ### end Alembic commands ###
