"""add daily_activity table

Revision ID: 0563d6d01623
Revises: 0493fe4fb600
Create Date: 2026-09-03 08:43:05.277134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0563d6d01623'
down_revision: Union[str, Sequence[str], None] = '0493fe4fb600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity',
    sa.Column('installation_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('activity_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.PrimaryKeyConstraint('installation_id', 'activity_date', name='pk_daily_activity')
    )
    op.create_index(op.f('ix_daily_activity_activity_date'), 'daily_activity', ['activity_date'], unique=False)
    op.create_index(op.f('ix_daily_activity_installation_id'), 'daily_activity', ['installation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_activity_installation_id'), table_name='daily_activity')
    op.drop_index(op.f('ix_daily_activity_activity_date'), table_name='daily_activity')
    op.drop_table('daily_activity')
    # ### end Alembic commands ###
