"""create installation table

Revision ID: 451846b5ec41
Revises: 
Create Date: 2026-08-28 15:53:20.691349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from app.models import UtcDateTime


# revision identifiers, used by Alembic.
revision: str = '451846b5ec41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation',
    sa.Column('installation_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('os', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('architecture', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('runtime', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', UtcDateTime(), nullable=True),
    sa.Column('last_seen_at', UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('installation_id')
    )
    op.create_index(op.f('ix_installation_architecture'), 'installation', ['architecture'], unique=False)
    op.create_index(op.f('ix_installation_first_seen_at'), 'installation', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_installation_last_seen_at'), 'installation', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_installation_os'), 'installation', ['os'], unique=False)
    op.create_index(op.f('ix_installation_version'), 'installation', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installation_version'), table_name='installation')
    op.drop_index(op.f('ix_installation_os'), table_name='installation')
    op.drop_index(op.f('ix_installation_last_seen_at'), table_name='installation')
    op.drop_index(op.f('ix_installation_first_seen_at'), table_name='installation')
    op.drop_index(op.f('ix_installation_architecture'), table_name='installation')
    op.drop_table('installation')
    # ### end Alembic commands ###
