"""add message_version to installation

Revision ID: aa0cf63c193c
Revises: 451846b5ec41
Create Date: 2026-08-28 22:52:16.419774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0cf63c193c'
down_revision: Union[str, Sequence[str], None] = '451846b5ec41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installation', sa.Column('message_version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installation', 'message_version')
    # ### end Alembic commands ###
