"""add pruned_installation table

Revision ID: c998c87a60cf
Revises: aa0cf63c193c
Create Date: 2026-08-31 12:04:20.307475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from app.models import UtcDateTime


# revision identifiers, used by Alembic.
revision: str = 'c998c87a60cf'
down_revision: Union[str, Sequence[str], None] = 'aa0cf63c193c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pruned_installation',
    sa.Column('installation_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('pruned_at', UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('installation_id')
    )
    op.create_index(op.f('ix_pruned_installation_pruned_at'), 'pruned_installation', ['pruned_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pruned_installation_pruned_at'), table_name='pruned_installation')
    op.drop_table('pruned_installation')
    # ### end Alembic commands ###
